#pragma kernel FillEmpty
#pragma kernel Sphere

float4 _StartPos;
uint _count;
float _Brush_Size;

RWStructuredBuffer<float4> Colors;
RWStructuredBuffer<float3> Vertices;

[numthreads(1,1,1)]
void Sphere (uint3 id : SV_DispatchThreadID)
{
    for (uint i = 0; i < _count; i ++)
    {
    	Colors[i]= float4(1,1,1,1);
    }
}

[numthreads(1,1,1)]
void FillEmpty (uint3 id : SV_DispatchThreadID)
{
	Colors[id.x]=(float4)0;
}